#![no_std]
//! # Buzzer
//!
//! ## Overview
//! This driver provides and abstraction over LEDC to drive a piezo-electric
//! buzzer.
//!
//! The [songs] submodule contains pre-programmed songs to play through
//! the buzzer.

use embedded_hal::prelude::_embedded_hal_blocking_delay_DelayMs;
use esp_hal_common::{
    clock::Clocks,
    gpio::OutputPin,
    ledc::{
        channel::{self, Channel, ChannelIFace},
        timer::{self, Timer, TimerHW, TimerIFace, TimerSpeed},
        LowSpeed,
        LEDC,
    },
    peripheral::{Peripheral, PeripheralRef},
    peripherals,
    Delay,
};
use fugit::RateExtU32;

/// Errors from Buzzer
#[derive(Debug)]
pub enum Error {
    /// Errors from [channel::Error]
    Channel(channel::Error),

    /// Errors from [timer::Error]
    Timer(timer::Error),

    /// Error when the volume pin isn't set and we try to use it
    VolumeNotSet,

    /// When the volume level is out of range. Either too low or too high.
    VolumeOutOfRange,
}

/// Converts [channel::Error] into [self::Error]
impl From<channel::Error> for Error {
    fn from(error: channel::Error) -> Self {
        Error::Channel(error)
    }
}

/// Converts [timer::Error] into [self::Error]
impl From<timer::Error> for Error {
    fn from(error: timer::Error) -> Self {
        Error::Timer(error)
    }
}

/// Represents a tone value to play through the buzzer
pub struct ToneValue {
    /// Note of the tone in Hz  
    /// *Use 0 for a silent tone*
    pub note: u32,

    /// Duration for the note in ms
    pub duration: u32,
}

/// Represents different volume strategies for the buzzer.
///
/// - [VolumeType::OnOff] is a simple on or off volume. It's similar as using
///   `.mute()`
/// except that the volume control is on a second pin independant of the buzzer.
///
/// - [VolumeType::Duty] uses the duty as the volume control. It acts like a PWM
/// by switching the power off and off. This may require extra logic gates in
/// the circuit.
pub enum VolumeType {
    /// An On / Off based volume
    OnOff,

    /// A duty based volume where 0% is the lowest and 100% the highest.
    Duty,
}

/// Volume configuration for the buzzer
struct Volume<'a, V: OutputPin> {
    /// Output pin for the volume
    volume_pin: PeripheralRef<'a, V>,

    /// Type of the volume
    volume_type: VolumeType,

    /// Volume level
    ///
    /// For [VolumeType::OnOff], should be 0 for Off, or 1 or more for On
    /// For [VolumeType::Duty], should be between 1 and 99.
    level: u8,
}

pub struct Buzzer<'a, S: TimerSpeed, O: OutputPin, V: OutputPin> {
    timer: Timer<'a, S>,
    channel_number: channel::Number,
    output_pin: PeripheralRef<'a, O>,
    delay: Delay,
    volume: Option<Volume<'a, V>>,
    clocks: &'a Clocks<'a>,
}

impl<'a, S: TimerSpeed, O: OutputPin + Peripheral<P = O>, V: OutputPin + Peripheral<P = V>>
    Buzzer<'a, S, O, V>
where
    S: TimerSpeed<ClockSourceType = timer::LSClockSource>,
    Timer<'a, S>: TimerHW<S>,
    Timer<'a, S>: TimerIFace<LowSpeed>,
{
    /// Create a new buzzer for the given pin
    pub fn new(
        ledc: &'a LEDC,
        timer_number: timer::Number,
        channel_number: channel::Number,
        output_pin: impl Peripheral<P = O> + 'a,
        clocks: &'a Clocks,
    ) -> Self {
        let timer = ledc.get_timer(timer_number);
        Self {
            timer,
            channel_number,
            output_pin: output_pin.into_ref(),
            delay: Delay::new(clocks),
            volume: None::<Volume<'a, V>>,
            clocks,
        }
    }

    /// Add a volume control for the buzzer.
    pub fn with_volume(
        &mut self,
        volume_pin: impl Peripheral<P = V> + 'a,
        volume_type: VolumeType,
    ) {
        self.volume = Some(Volume {
            volume_pin: volume_pin.into_ref(),
            volume_type,
            level: 50,
        });
    }

    /// Set the volume of the buzzer
    ///
    /// For [VolumeType::Duty], the level should be between 0 and 99.
    /// For [VolumeType::OnOff], it will only be mute on 0 and playing on 1 or
    /// more
    pub fn set_volume(&mut self, level: u8) -> Result<(), Error> {
        if let Some(ref mut volume) = self.volume {
            match volume.volume_type {
                VolumeType::OnOff => {
                    let is_high = if level != 0 { true } else { false };
                    // Only turn off when level is set to 0, else set to high
                    volume.volume_pin.set_to_push_pull_output();
                    volume.volume_pin.set_output_high(is_high);
                    Ok(())
                }
                VolumeType::Duty => {
                    // Ensure that the volume is between 0 inclusively and 100 exclusively.
                    if !(0..100).contains(&level) {
                        return Err(Error::VolumeOutOfRange);
                    }
                    volume.level = level;
                    // Put a dummy config in the timer if it's not already configured
                    if !self.timer.is_configured() {
                        self.timer.configure(timer::config::Config {
                            duty: timer::config::Duty::Duty10Bit,
                            clock_source: timer::LSClockSource::APBClk,
                            frequency: 10.Hz(),
                        })?;
                    }
                    let ledc = unsafe { &*crate::peripherals::LEDC::ptr() };
                    let mut channel = Channel {
                        ledc,
                        timer: None,
                        number: self.channel_number,
                        output_pin: volume.volume_pin.reborrow(),
                    };

                    channel
                        .configure(channel::config::Config {
                            timer: &self.timer,
                            duty_pct: level,
                            pin_config: channel::config::PinConfig::PushPull,
                        })
                        .map_err(|e| e.into())
                }
            }
        } else {
            return Err(Error::VolumeNotSet);
        }
    }

    /// Mute the buzzer
    ///
    /// The muting is done by simply setting the duty to 100
    pub fn mute(&mut self) -> Result<(), Error> {
        let ledc = unsafe { &*crate::peripherals::LEDC::ptr() };
        let mut channel = Channel {
            ledc,
            timer: None,
            number: self.channel_number,
            output_pin: self.output_pin.reborrow(),
        };

        channel
            .configure(channel::config::Config {
                timer: &self.timer,
                duty_pct: 100,
                pin_config: channel::config::PinConfig::PushPull,
            })
            .map_err(|e| e.into())
    }

    /// Play a frequency through the buzzer
    pub fn play(&mut self, frequency: u32) -> Result<(), Error> {
        let ledc = unsafe { &*crate::peripherals::LEDC::ptr() };

        let mut channel = Channel {
            ledc,
            timer: None,
            number: self.channel_number,
            output_pin: self.output_pin.reborrow(),
        };

        // Max duty resolution for a frequency:
        // Integer(log2(LEDC_APB_CKL / frequency))
        let mut result = 0;
        let mut value = (self.clocks.apb_clock / frequency).raw();

        // Limit duty resolution to 14 bits
        while value > 1 && result < 14 {
            value >>= 1;
            result += 1;
        }

        self.timer.configure(timer::config::Config {
            duty: timer::config::Duty::from(result),
            clock_source: timer::LSClockSource::APBClk,
            frequency: frequency.Hz(),
        })?;

        channel.configure(channel::config::Config {
            timer: &self.timer,
            // Use volume as duty if set since we use the same channel.
            duty_pct: self.volume.as_ref().map_or(50, |v| v.level),
            pin_config: channel::config::PinConfig::PushPull,
        })?;

        Ok(())
    }

    /// Play a sound sequence through the buzzer
    ///
    /// Uses a pair of frequencies and timings to play a sound sequence.
    ///
    /// # Arguments
    /// * `sequence` - A list of frequencies to play through the buzzer
    /// * `timings` - A list of timings in ms for each frequencies
    ///
    /// # Examples
    /// Play a single note at 300Hz for 1 second
    /// ```
    /// buzzer.play_song([300], [1000]);
    /// ```
    ///
    /// Play a sequence of 3 beeps with a break inbetween
    /// ```
    /// buzzer.play_song([200, 0, 200, 0, 200], [200, 50, 200, 50, 200]);
    /// ```
    ///
    /// Play a sequence of 3 notes with the same duration
    /// ```
    /// buzzer.play_song([100, 200 300], [100; 3]);
    /// ```
    ///
    /// # Errors
    /// This function returns an [Error] in case of an error.
    /// An error can occur when an invalid value is used as a tone
    pub fn play_song<const T: usize>(
        &mut self,
        sequence: [u32; T],
        timings: [u32; T],
    ) -> Result<(), Error> {
        // Iterate for each note / timing pair
        for (note, timing) in sequence.iter().zip(timings.iter()) {
            // Mute if note is 0Hz
            if *note == 0 {
                self.mute()?;
            } else {
                self.play(*note)?;
            }
            self.delay.delay_ms(*timing);
            self.mute()?;
        }
        // Mute at the end of the sequence
        self.mute()
    }

    /// Play a tone sequence through the buzzer
    ///
    /// Uses a pair of frequencies and timings to play a sound sequence.
    ///
    /// # Arguments
    /// * `tones` - A list of type [ToneValue] to play through the buzzer
    ///
    /// # Examples
    /// Play a tone sequence
    /// ```
    /// let song = [
    ///     buzzer::ToneValue {
    ///         note: 100,
    ///         duration: 100,
    ///     },
    ///     buzzer::ToneValue {
    ///         note: 200,
    ///         duration: 100,
    ///     },
    ///     buzzer::ToneValue {
    ///         note: 300,
    ///         duration: 100,
    ///     },
    /// ];
    /// buzzer.play_tones(song);
    /// ```
    ///
    /// # Errors
    /// This function returns an [Error] in case of an error.
    /// An error can occur when an invalid value is used as a tone
    pub fn play_tones<const T: usize>(&mut self, tones: [ToneValue; T]) -> Result<(), Error> {
        let mut sequence: [u32; T] = [0; T];
        let mut timings: [u32; T] = [0; T];
        for (index, tone) in tones.iter().enumerate() {
            sequence[index] = tone.note;
            timings[index] = tone.duration;
        }
        self.play_song(sequence, timings)
    }
}

/// Modules for songs that can be played on the buzzer
pub mod songs {
    #![allow(unused)]

    use super::ToneValue;

    /// Generate a ToneValue slice from Song beats and tempo
    macro_rules! song {
        ($tempo:expr, [$(($note:expr, $duration:expr)),*]) => {
            {
                const WHOLENOTE: u32 = (60_000 * 4) / $tempo;
            [
                $(
                    ToneValue { note: $note, duration: WHOLENOTE / $duration },
                )*
            ]
            }
        };
    }

    // Note values in Hz
    const NOTE_B0: u32 = 31;
    const NOTE_C1: u32 = 33;
    const NOTE_CS1: u32 = 35;
    const NOTE_D1: u32 = 37;
    const NOTE_DS1: u32 = 39;
    const NOTE_E1: u32 = 41;
    const NOTE_F1: u32 = 44;
    const NOTE_FS1: u32 = 46;
    const NOTE_G1: u32 = 49;
    const NOTE_GS1: u32 = 52;
    const NOTE_A1: u32 = 55;
    const NOTE_AS1: u32 = 58;
    const NOTE_B1: u32 = 62;
    const NOTE_C2: u32 = 65;
    const NOTE_CS2: u32 = 69;
    const NOTE_D2: u32 = 73;
    const NOTE_DS2: u32 = 78;
    const NOTE_E2: u32 = 82;
    const NOTE_F2: u32 = 87;
    const NOTE_FS2: u32 = 93;
    const NOTE_G2: u32 = 98;
    const NOTE_GS2: u32 = 104;
    const NOTE_A2: u32 = 110;
    const NOTE_AS2: u32 = 117;
    const NOTE_B2: u32 = 123;
    const NOTE_C3: u32 = 131;
    const NOTE_CS3: u32 = 139;
    const NOTE_D3: u32 = 147;
    const NOTE_DS3: u32 = 156;
    const NOTE_E3: u32 = 165;
    const NOTE_F3: u32 = 175;
    const NOTE_FS3: u32 = 185;
    const NOTE_G3: u32 = 196;
    const NOTE_GS3: u32 = 208;
    const NOTE_A3: u32 = 220;
    const NOTE_AS3: u32 = 233;
    const NOTE_B3: u32 = 247;
    const NOTE_C4: u32 = 262;
    const NOTE_CS4: u32 = 277;
    const NOTE_D4: u32 = 294;
    const NOTE_DS4: u32 = 311;
    const NOTE_E4: u32 = 330;
    const NOTE_F4: u32 = 349;
    const NOTE_FS4: u32 = 370;
    const NOTE_G4: u32 = 392;
    const NOTE_GS4: u32 = 415;
    const NOTE_A4: u32 = 440;
    const NOTE_AS4: u32 = 466;
    const NOTE_B4: u32 = 494;
    const NOTE_C5: u32 = 523;
    const NOTE_CS5: u32 = 554;
    const NOTE_D5: u32 = 587;
    const NOTE_DS5: u32 = 622;
    const NOTE_E5: u32 = 659;
    const NOTE_F5: u32 = 698;
    const NOTE_FS5: u32 = 740;
    const NOTE_G5: u32 = 784;
    const NOTE_GS5: u32 = 831;
    const NOTE_A5: u32 = 880;
    const NOTE_AS5: u32 = 932;
    const NOTE_B5: u32 = 988;
    const NOTE_C6: u32 = 1047;
    const NOTE_CS6: u32 = 1109;
    const NOTE_D6: u32 = 1175;
    const NOTE_DS6: u32 = 1245;
    const NOTE_E6: u32 = 1319;
    const NOTE_F6: u32 = 1397;
    const NOTE_FS6: u32 = 1480;
    const NOTE_G6: u32 = 1568;
    const NOTE_GS6: u32 = 1661;
    const NOTE_A6: u32 = 1760;
    const NOTE_AS6: u32 = 1865;
    const NOTE_B6: u32 = 1976;
    const NOTE_C7: u32 = 2093;
    const NOTE_CS7: u32 = 2217;
    const NOTE_D7: u32 = 2349;
    const NOTE_DS7: u32 = 2489;
    const NOTE_E7: u32 = 2637;
    const NOTE_F7: u32 = 2794;
    const NOTE_FS7: u32 = 2960;
    const NOTE_G7: u32 = 3136;
    const NOTE_GS7: u32 = 3322;
    const NOTE_A7: u32 = 3520;
    const NOTE_AS7: u32 = 3729;
    const NOTE_B7: u32 = 3951;
    const NOTE_C8: u32 = 4186;
    const NOTE_CS8: u32 = 4435;
    const NOTE_D8: u32 = 4699;
    const NOTE_DS8: u32 = 4978;
    const REST: u32 = 0;

    // Note durations
    const NOTE: u32 = 1;
    const DOTTED_NOTE: u32 = NOTE - NOTE / 2;
    const HALF_NOTE: u32 = 2;
    const DOTTED_HALF_NOTE: u32 = HALF_NOTE - HALF_NOTE / 2;
    const QUARTER_NOTE: u32 = 4;
    const DOTTED_QUARTER_NOTE: u32 = QUARTER_NOTE - QUARTER_NOTE / 2;
    const EIGHTEENTH_NOTE: u32 = 8;
    const DOTTED_EIGHTEENTH_NOTE: u32 = EIGHTEENTH_NOTE - EIGHTEENTH_NOTE / 2;
    const SIXTEENTH_NOTE: u32 = 16;
    const DOTTED_SIXTEENTH_NOTE: u32 = SIXTEENTH_NOTE - SIXTEENTH_NOTE / 2;
    const THIRTYSECOND_NOTE: u32 = 32;
    const DOTTED_THIRTYSECOND_NOTE: u32 = THIRTYSECOND_NOTE - THIRTYSECOND_NOTE / 2;

    pub const DOOM: [ToneValue; 680] = song!(
        225,
        [
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_FS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_FS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_FS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_FS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_DS3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_DS3, DOTTED_HALF_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_DS3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_C4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_CS4, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_B3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_CS3, EIGHTEENTH_NOTE),
            (NOTE_GS3, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_B3, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_F3, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_FS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_DS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_FS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_DS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_DS4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_DS3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_DS3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_F3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_G3, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A2, EIGHTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_C4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_F3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_D3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, DOTTED_HALF_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_AS2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B2, EIGHTEENTH_NOTE),
            (NOTE_C3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_D3, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_E2, EIGHTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B2, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_C4, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_G3, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E3, DOTTED_SIXTEENTH_NOTE)
        ]
    );

    pub const FURELISE: [ToneValue; 603] = song!(
        80,
        [
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_G4, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_F4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_E6, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_G4, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_F4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_E6, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_F5, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_AS5, DOTTED_SIXTEENTH_NOTE),
            (NOTE_A5, THIRTYSECOND_NOTE),
            (NOTE_A5, SIXTEENTH_NOTE),
            (NOTE_G5, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_AS4, EIGHTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, THIRTYSECOND_NOTE),
            (NOTE_G4, THIRTYSECOND_NOTE),
            (NOTE_A4, THIRTYSECOND_NOTE),
            (NOTE_B4, THIRTYSECOND_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_D5, DOTTED_SIXTEENTH_NOTE),
            (NOTE_B4, THIRTYSECOND_NOTE),
            (NOTE_C5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_G4, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_A4, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_B4, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_C5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_D5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_C6, THIRTYSECOND_NOTE),
            (NOTE_B5, THIRTYSECOND_NOTE),
            (NOTE_A5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_D5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_D5, THIRTYSECOND_NOTE),
            (NOTE_C5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_G4, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_A4, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_B4, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_C5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_D5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_C6, THIRTYSECOND_NOTE),
            (NOTE_B5, THIRTYSECOND_NOTE),
            (NOTE_A5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_D5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_D5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_DS5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_B4, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_DS5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_B4, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_DS5, THIRTYSECOND_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_G4, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_F4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_E6, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_F5, QUARTER_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, DOTTED_QUARTER_NOTE),
            (NOTE_CS5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_F5, QUARTER_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_F5, DOTTED_QUARTER_NOTE),
            (NOTE_DS5, QUARTER_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_AS4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_GS4, QUARTER_NOTE),
            (NOTE_G4, EIGHTEENTH_NOTE),
            (NOTE_A4, DOTTED_QUARTER_NOTE),
            (NOTE_B4, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_A3, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_D5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_B4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_D6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_B5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_D6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C6, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_B5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_AS5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_GS5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_G5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_FS5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_F5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_DS5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_D5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_CS5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_C5, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_B4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_AS4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_A4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_GS4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_G4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_FS4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_F4, DOTTED_THIRTYSECOND_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (REST, DOTTED_EIGHTEENTH_NOTE),
            (REST, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_G4, SIXTEENTH_NOTE),
            (NOTE_F5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (REST, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E6, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_GS4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (REST, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_E5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C4, SIXTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E4, SIXTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, DOTTED_QUARTER_NOTE)
        ]
    );

    pub const NEVER_GONNA_GIVE_YOU_UP: [ToneValue; 340] = song!(
        114,
        [
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_FS5, DOTTED_QUARTER_NOTE),
            (NOTE_A5, SIXTEENTH_NOTE),
            (NOTE_G5, SIXTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, HALF_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_FS5, DOTTED_QUARTER_NOTE),
            (NOTE_A5, SIXTEENTH_NOTE),
            (NOTE_G5, SIXTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, HALF_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (REST, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, HALF_NOTE),
            (REST, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, DOTTED_QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, HALF_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_CS5, SIXTEENTH_NOTE),
            (NOTE_B4, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A5, QUARTER_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_CS5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (REST, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, DOTTED_QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, DOTTED_QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, QUARTER_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, DOTTED_QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_CS5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A5, QUARTER_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_CS5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A5, QUARTER_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_CS5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_FS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A5, QUARTER_NOTE),
            (NOTE_CS5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_CS5, SIXTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, SIXTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_CS5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (REST, QUARTER_NOTE)
        ]
    );

    pub const PACMAN: [ToneValue; 31] = song!(
        105,
        [
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_B5, SIXTEENTH_NOTE),
            (NOTE_FS5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_B5, THIRTYSECOND_NOTE),
            (NOTE_FS5, DOTTED_SIXTEENTH_NOTE),
            (NOTE_DS5, EIGHTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_C6, SIXTEENTH_NOTE),
            (NOTE_G6, SIXTEENTH_NOTE),
            (NOTE_E6, SIXTEENTH_NOTE),
            (NOTE_C6, THIRTYSECOND_NOTE),
            (NOTE_G6, DOTTED_SIXTEENTH_NOTE),
            (NOTE_E6, EIGHTEENTH_NOTE),
            (NOTE_B4, SIXTEENTH_NOTE),
            (NOTE_B5, SIXTEENTH_NOTE),
            (NOTE_FS5, SIXTEENTH_NOTE),
            (NOTE_DS5, SIXTEENTH_NOTE),
            (NOTE_B5, THIRTYSECOND_NOTE),
            (NOTE_FS5, DOTTED_SIXTEENTH_NOTE),
            (NOTE_DS5, EIGHTEENTH_NOTE),
            (NOTE_DS5, THIRTYSECOND_NOTE),
            (NOTE_E5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_F5, THIRTYSECOND_NOTE),
            (NOTE_FS5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_G5, THIRTYSECOND_NOTE),
            (NOTE_GS5, THIRTYSECOND_NOTE),
            (NOTE_A5, SIXTEENTH_NOTE),
            (NOTE_B5, EIGHTEENTH_NOTE)
        ]
    );

    pub const STAR_WARS: [ToneValue; 88] = song!(
        108,
        [
            (NOTE_AS4, EIGHTEENTH_NOTE),
            (NOTE_AS4, EIGHTEENTH_NOTE),
            (NOTE_AS4, EIGHTEENTH_NOTE),
            (NOTE_F5, HALF_NOTE),
            (NOTE_C6, HALF_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F6, HALF_NOTE),
            (NOTE_C6, QUARTER_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F6, HALF_NOTE),
            (NOTE_C6, QUARTER_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_G5, HALF_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_F5, HALF_NOTE),
            (NOTE_C6, HALF_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F6, HALF_NOTE),
            (NOTE_C6, QUARTER_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F6, HALF_NOTE),
            (NOTE_C6, QUARTER_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_G5, HALF_NOTE),
            (NOTE_C5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_C5, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C5, SIXTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_C6, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_G5, SIXTEENTH_NOTE),
            (NOTE_G5, HALF_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_AS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_G5, QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_C6, DOTTED_EIGHTEENTH_NOTE),
            (NOTE_C6, SIXTEENTH_NOTE),
            (NOTE_F6, QUARTER_NOTE),
            (NOTE_DS6, EIGHTEENTH_NOTE),
            (NOTE_CS6, QUARTER_NOTE),
            (NOTE_C6, EIGHTEENTH_NOTE),
            (NOTE_AS5, QUARTER_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_G5, QUARTER_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_C6, NOTE)
        ]
    );

    pub const TAKE_ON_ME: [ToneValue; 128] = song!(
        140,
        [
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_B5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_B5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_B5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_GS5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_B5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_A5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE),
            (NOTE_FS5, EIGHTEENTH_NOTE),
            (NOTE_E5, EIGHTEENTH_NOTE)
        ]
    );

    pub const TETRIS: [ToneValue; 99] = song!(
        144,
        [
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, DOTTED_QUARTER_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_A5, QUARTER_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, DOTTED_QUARTER_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, EIGHTEENTH_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, DOTTED_QUARTER_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_A5, QUARTER_NOTE),
            (NOTE_G5, EIGHTEENTH_NOTE),
            (NOTE_F5, EIGHTEENTH_NOTE),
            (NOTE_E5, DOTTED_QUARTER_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_D5, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_B4, QUARTER_NOTE),
            (NOTE_B4, EIGHTEENTH_NOTE),
            (NOTE_C5, EIGHTEENTH_NOTE),
            (NOTE_D5, QUARTER_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (NOTE_A4, QUARTER_NOTE),
            (REST, QUARTER_NOTE),
            (NOTE_E5, HALF_NOTE),
            (NOTE_C5, HALF_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_B4, HALF_NOTE),
            (NOTE_C5, HALF_NOTE),
            (NOTE_A4, HALF_NOTE),
            (NOTE_GS4, HALF_NOTE),
            (NOTE_B4, QUARTER_NOTE),
            (REST, EIGHTEENTH_NOTE),
            (NOTE_E5, HALF_NOTE),
            (NOTE_C5, HALF_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_B4, HALF_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_E5, QUARTER_NOTE),
            (NOTE_A5, HALF_NOTE),
            (NOTE_GS5, HALF_NOTE)
        ]
    );
    pub const ZELDA_LULLABY: [ToneValue; 48] = song!(
        108,
        [
            (NOTE_E4, HALF_NOTE),
            (NOTE_G4, QUARTER_NOTE),
            (NOTE_D4, HALF_NOTE),
            (NOTE_C4, EIGHTEENTH_NOTE),
            (NOTE_D4, EIGHTEENTH_NOTE),
            (NOTE_E4, HALF_NOTE),
            (NOTE_G4, QUARTER_NOTE),
            (NOTE_D4, DOTTED_HALF_NOTE),
            (NOTE_E4, HALF_NOTE),
            (NOTE_G4, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_G4, HALF_NOTE),
            (NOTE_F4, EIGHTEENTH_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_D4, DOTTED_HALF_NOTE),
            (NOTE_E4, HALF_NOTE),
            (NOTE_G4, QUARTER_NOTE),
            (NOTE_D4, HALF_NOTE),
            (NOTE_C4, EIGHTEENTH_NOTE),
            (NOTE_D4, EIGHTEENTH_NOTE),
            (NOTE_E4, HALF_NOTE),
            (NOTE_G4, QUARTER_NOTE),
            (NOTE_D4, DOTTED_HALF_NOTE),
            (NOTE_E4, HALF_NOTE),
            (NOTE_G4, QUARTER_NOTE),
            (NOTE_D5, HALF_NOTE),
            (NOTE_C5, QUARTER_NOTE),
            (NOTE_G4, HALF_NOTE),
            (NOTE_F4, EIGHTEENTH_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_F4, EIGHTEENTH_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_C4, HALF_NOTE),
            (NOTE_F4, HALF_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_D4, EIGHTEENTH_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_D4, EIGHTEENTH_NOTE),
            (NOTE_A3, HALF_NOTE),
            (NOTE_G4, HALF_NOTE),
            (NOTE_F4, EIGHTEENTH_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_F4, EIGHTEENTH_NOTE),
            (NOTE_E4, EIGHTEENTH_NOTE),
            (NOTE_C4, QUARTER_NOTE),
            (NOTE_F4, QUARTER_NOTE),
            (NOTE_C5, DOTTED_HALF_NOTE)
        ]
    );
}
